### ISSUE TITLE
Generating/Storing Solvable Levels

### ISSUE THREAD

**Issue by mattThousand** [NiceThings/ShinShikaku#29]
A "solvable" level consists of an X x Y grid that can be completely filled with rectangles (for example, a 10 x 7 grid with 3 rectangles of sizes 10 x 2, 12 x 2, and 13 x 2).

The first release of `Shin Shikaku` will contain, say `20` levels of increasing difficulty. 

1. How should these levels be generated? 
2. How should these levels be stored and accessed?

**Comment by ateliercw** [comment]
For generation: http://www.roguebasin.com/index.php?title=Basic_BSP_Dungeon_generation
Randomly choose a cell (first cell is a random chose of one option), randomly decide if you want to split horizontally or vertically, choose a random axis to split on, repeat N times for a complexity. Re-run the random split if the chosen cell / or axis cannot be split again.  Once you have your cells, choose a random tile within each cell to be the labelled tile.

For storage, make it decodable then shove it in a .plist or .json file. That also means you could have base levels then offer daily / weekly levels that cycle via an AWS bucket or iCloud storage.

**Comment by mattThousand** [comment]
aha, yes, that's the idea behind https://github.com/NiceThings/mondrian, which came about from me asking you the exact same question over lunch sometime in prehistory

**Comment by ateliercw** [comment]
:+1: I remembered having this discussion before.

**Comment by mattThousand** [comment]
👍 👍 🌮 🎉
